APP_COLOR_THEME = "dark"
APP_WIDGETS_COLORS = "dark-blue"

MAIN_WINDOW_NAME = "SaveIt: Personal Video Logger"
MAIN_WINDOW_HEIGHT = 620
MAIN_WINDOW_WIDTH = 1200
RIGHT_FRAME_WIDTH = 300

GOJECT_SELECTION_WINDOW_NAME = "{} - Gojects Selection".format(MAIN_WINDOW_NAME)
GOJECT_SELECTION_WINDOW_WIDTH = 650
GOJECT_SELECTION_WINDOW_HEIGHT = 650

GOJECT_EDIT_WINDOW_NAME = "{} - Gojects Settings".format(MAIN_WINDOW_NAME)
GOJECT_EDIT_WINDOW_WIDTH = 650
GOJECT_EDIT_WINDOW_HEIGHT = 650

PROCESS_DATA_WINDOW_NAME = "{} - Process Data".format(MAIN_WINDOW_NAME)
PROCESS_DATA_WINDOW_WIDTH = 400
PROCESS_DATA_WINDOW_HEIGHT = 200

DEFAULT_MIN_QUICKLOG_TIME = 15
DEFAULT_MAX_QUICKLOG_TIME = 50

DEFAULT_MIN_LONGLOG_TIME = 60
DEFAULT_MAX_LONGLOG_TIME = 180

WAIT_TO_CLEAN_TIME = 5

COLORS = {
    "Backlog": "blue",
    "In Progress": "orange",
    "Completed": "green"
} 

TOPICS = {
    "BOOKS": "BOOKS",
    "ARTIFICIAL_INTELLIGENCE": "ARTIFICIAL_INTELLIGENCE",
    "PROGRAMMING": "PROGRAMMING",
    "COMPUTER_SCIENCE": "COMPUTER_SCIENCE",
    "MATHEMATICS": "MATHEMATICS",
    "NEUROSCIENCE": "NEUROSCIENCE",
    "ELECTRONIC": "ELECTRONIC",
    "QUANTUM_PHYSICS": "QUANTUM_PHYSICS",
    "MUSIC": "MUSIC",
    "PHOTOGRAPHY_DESIGN": "PHOTOGRAPHY_DESIGN", 
    "DRAWING_PAINTING": "DRAWING_PAINTING",
    "WRITING": "WRITING",    
    "SPORTS_HEALTH": "SPORTS_HEALTH", 
    "FINANCE": "FINANCE",
    "ENTREPRENEURSHIP": "ENTREPRENEURSHIP", 
    "LANGUAGES": "LANGUAGES"              
    }