from src.goject import Topic

HEIGHT = 620
WIDTH = 1200
RIGHT_FRAME_WIDTH = 300

COLORS = {
    "Backlog": "blue",
    "In Progress": "orange",
    "Completed": "green"
} 

TOPICS = {
    Topic.BOOKS: "BOOKS",
    Topic.ARTIFICIAL_INTELLIGENCE: "ARTIFICIAL_INTELLIGENCE",
    Topic.PROGRAMMING: "PROGRAMMING",
    Topic.COMPUTER_SCIENCE: "COMPUTER_SCIENCE",
    Topic.MATHEMATICS: "MATHEMATICS",
    Topic.NEUROSCIENCE: "NEUROSCIENCE",
    Topic.ELECTRONIC: "ELECTRONIC",
    Topic.QUANTUM_PHYSICS: "QUANTUM_PHYSICS",
    Topic.MUSIC: "MUSIC",
    Topic.PHOTOGRAPHY_DESIGN: "PHOTOGRAPHY_DESIGN", 
    Topic.DRAWING_PAINTING: "DRAWING_PAINTING",
    Topic.WRITING: "WRITING",    
    Topic.SPORTS_HEALTH: "SPORTS_HEALTH", 
    Topic.FINANCE: "FINANCE",
    Topic.ENTREPRENEURSHIP: "ENTREPRENEURSHIP", 
    Topic.LANGUAGES: "LANGUAGES",
    "BOOKS": "BOOKS",
    "ARTIFICIAL_INTELLIGENCE": "ARTIFICIAL_INTELLIGENCE",
    "PROGRAMMING": "PROGRAMMING",
    "COMPUTER_SCIENCE": "COMPUTER_SCIENCE",
    "MATHEMATICS": "MATHEMATICS",
    "NEUROSCIENCE": "NEUROSCIENCE",
    "ELECTRONIC": "ELECTRONIC",
    "QUANTUM_PHYSICS": "QUANTUM_PHYSICS",
    "MUSIC": "MUSIC",
    "PHOTOGRAPHY_DESIGN": "PHOTOGRAPHY_DESIGN", 
    "DRAWING_PAINTING": "DRAWING_PAINTING",
    "WRITING": "WRITING",    
    "SPORTS_HEALTH": "SPORTS_HEALTH", 
    "FINANCE": "FINANCE",
    "ENTREPRENEURSHIP": "ENTREPRENEURSHIP", 
    "LANGUAGES": "LANGUAGES"              
    }